#! /bin/bash

a=`find /root/project -xdev -type f | egrep -i '.zip|.jar' | awk {print} ORS=", " | sed 's/, $//'` 
b=`date +%d-%m-%Y`

sed -i "s|import.archive.path=.*|import.archive.path=${a}|" test1

tar -cvzf /root/archive/"project_$b.tar.gz" /root/project
